# encoding: utf-8
---
recipe:
  Rx: config
  args:
    - schema=pinyin
  description: >-
    Customize input schema to enable double_pinyin.
      - double_pinyin_flypy（小鹤双拼）
      - double_pinyin（自然码双拼）
      - double_pinyin_mspy（微软双拼）
      - double_pinyin_sogou（搜狗双拼）
      - double_pinyin_abc（智能 ABC 双拼）
      - double_pinyin_ziguang（紫光双拼）
      - double_pinyin_jiajia（拼音加加）

patch_files:
  radical_pinyin.custom.yaml:
    - patch/+:
        speller/algebra:
          __include: radical_pinyin.schema.yaml:/algebra_${schema:-pinyin}